# fly.toml file generated for edc-pihole-tailscale on 2022-08-20T12:08:09-04:00

app = "edc-pihole-tailscale"

[[services]]
  internal_port = 53
  protocol = "udp"

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
